service: monorepolambdas

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.6

functions:
  random_number:
    handler: src.random_number.random_number_handler.main
  round:
    handler: src.round.rounding_handler.main

plugins:

  - serverless-python-requirements

custom:

  pythonRequirements:

    dockerizePip: non-linux